id: I3752B356
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T22:56:58+00:00'
last_modified: '2022-06-08T12:45:20.513050+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13813
  title: བོད་ཀྱི་དཀར་ཆག་རིག་པའི་ལག་དེབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    367E:
      image_group_id: I1KG15799
      title: Volume 1 of bod kyi dkar chag rig pa'i lag deb/
      total_pages: 228
      order: 1
      base_file: 367E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
