id: P006942
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13813
  title: བོད་ཀྱི་དཀར་ཆག་རིག་པའི་ལག་དེབ།
  author: ''
  volumes:
    d5e2edcf5beb4c2287a89944f377548e:
      image_group_id: I1KG15799
      title: ''
      volume_number: 1
      total_pages: 228
ebook_metadata:
  title: བོད་ཀྱི་དཀར་ཆག་རིག་པའི་ལག་དེབ།
  author: ''
  sku: P006942
  cover: cover.jpg
  layers:
  - pagination
